spring:
  application:
    name: Shippex

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

whatsapp:
  access-token: ${WHATSAPP_ACCESS_TOKEN}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}
  api-version: ${WHATSAPP_API_VERSION:v23.0}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

  health:
    mongo:
      enabled: true
    redis:
      enabled: true